name: Go Build Multi-Platform

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64, arm]
        exclude:
          - goos: windows
            goarch: arm64
          - goos: windows
            goarch: arm
          - goos: darwin
            goarch: arm64
          - goos: darwin
            goarch: arm

    runs-on: ubuntu-latest

    outputs:
      build_complete: ${{ steps.build_step.outcome == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Build
      id: build_step
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        GOARM: ${{ matrix.goarch == 'arm' && '6' || '' }}
      run: |
        output_name="website-archiver-${GOOS}-${GOARCH}"
        if [ "$GOOS" = "windows" ]; then
          output_name+=".exe"
        fi
        if [ "$GOARCH" = "arm" ]; then
          output_name+="-v6"
        fi
        go build -v -ldflags="-s -w" -o "${output_name}" .
        echo "Built: ${output_name}"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: website-archiver-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goarch == 'arm' && '-v6' || '' }}
        path: website-archiver-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goarch == 'arm' && '-v6' || '' }}*

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    permissions:
      contents: write

    steps:
      - name: Download All Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release-assets

      - name: List downloaded files (for debugging)
        run: ls -R ./release-assets

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release-assets/*/*